---

- name: create kubeadm init config
  ansible.builtin.template:
    src: kubeadm.yaml.j2
    dest: /root/kubeadm.yaml

- name: kubeadm init
  command: kubeadm init --config /root/kubeadm.yaml --skip-phases=addon/kube-proxy

- name: create .kube config dir
  become: yes
  ansible.builtin.file:
    path: "/root/.kube"
    state: directory
    owner: root
    group: root
    mode: 0700

- name: copy k8 admin to user dir
  become: yes
  ansible.builtin.copy:
    remote_src: yes
    src: /etc/kubernetes/admin.conf
    dest: "/root/.kube/config"
    owner: root
    group: root
    mode: 0600

- name: Untaint master node so it can run pods
  ansible.builtin.command: kubectl taint node {{ k8s_command_node }} node-role.kubernetes.io/master:NoSchedule-
  when: k8s_master_can_run_pods
