---

- name: create kubeadm init config
  template:
    src: kubeadm.yaml
    dest: /root/kubeadm.yaml

- name: kubeadm init
  command: kubeadm init --config /root/kubeadm.yaml

- name: create .kube config dir
  become: yes
  file:
    path: "/root/.kube"
    state: directory
    owner: root
    group: root
    mode: 0700

- name: copy k8 admin to user dir
  become: yes
  copy:
    remote_src: yes
    src: /etc/kubernetes/admin.conf
    dest: "/root/.kube/config"
    owner: root
    group: root
    mode: 0600
