---
# tasks file for kubernetes master

- name: populate service facts
  service_facts:

- name: install apt packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
    state: present

- name: download google gpg keys
  uri:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    dest: /usr/share/keyrings/kubernetes-archive-keyring.gpg
    status_code:
      - 200
      - 304

- name: install google gpg keys
  blockinfile:
    path: /etc/apt/sources.list.d/kubernetes.list
    block: |
      deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main
    create: yes
    state: present

- name: install kubectl kubeadm and kubelet
  apt:
    name:
      - kubeadm={{ kubernetes_version }}-00
      - kubectl={{ kubernetes_version }}-00
      - kubelet={{ kubernetes_version }}-00
    allow_change_held_packages: true
    state: present
    update_cache: yes

- name: mark hold updates on k8s packages
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubeadm
    - kubectl
    - kubelet

#
# If the firewall is enabled you may see the following issue:
# Everything in the cluster looks like it's working, but you cannot
# connect to services backed by pods, or the pods themselves on the
# node(s) with the firewall running.
#
- name: disable firewall
  service:
    name: ufw
    state: stopped
    enabled: no
  when: "'ufw' in ansible_facts.services"
