---

- name: populate variables
  ansible.builtin.setup:

- name: Pre-config tasks
  include_tasks: pre-config.yaml

- name: common k8s setup tasks
  include_tasks: "{{ ansible_os_family | lower }}.yaml"

- name: enable and use kubelet
  service:
    name: kubelet
    state: started
    enabled: yes

- name: remove existing docker packages from base distro
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent

- name: update all packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: latest

- name: Controller config
  include_tasks: controller.yaml
  when: k8s_server_role == "controller"

- name: worker config
  include_tasks: workers.yaml
  when: k8s_server_role == "worker"