---
#
# If you have another OS on the device and it has swap you may need
# to run the following to permanently disable swap across reboots:
#sudo systemctl mask "dev-sdXX.swap"
#
- name: turn off swap now
  command: "swapoff -a"
- name: turn off swap in fstab
  mount:
    path: none
    fstype: 'swap'
    state: absent

- name: load br_netfilter
  community.general.modprobe:
    name: br_netfilter
    state: present
    persistent: present

- name: configure networking for kubernetes
  blockinfile:
    path: /etc/sysctl.d/kubernetes.conf
    block: |
      net.bridge.bridge-nf-call-ip6tables=1
      net.bridge.bridge-nf-call-iptables=1
      net.ipv6.conf.all.forwarding=1
      net.ipv4.conf.all.forwarding=1
    state: present
    create: yes
  notify: restart ubuntu sysctl
