---

ipa_directory_password: "{{ vault_ipa_directory_password }}"
ipa_admin_password: "{{ vault_ipa_admin_password }}"
ipa_admin_user: "admin"

ipa_new_user_password: "{{ vault_ipa_new_user_password }}"

ipa_groups:
  - name: app-gitea-admins
  - name: app-gitea-users

ipa_users:
  - name: bmilco
    first_name: Brian
    last_name: Milco
    loginshell: /usr/bin/zsh
    groups:
      - name: admins
      - name: app-gitea-admins
    emails:
      - "{{ site_admin_email }}"
    ssh_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPQGjMgHnJcTrRNNSFLFbiBFIf4LeG1R4rxq7mBuhWGk {{ site_admin_email }}
