---

- name: Add {{ item.name }} {{ item.type }}
  community.general.ipa_dnsrecord:
    ipa_host: "{{ ipa_hostname }}"
    ipa_user: "{{ ipa_admin_user }}"
    ipa_pass: "{{ ipa_admin_password }}"
    zone_name: "{{ item.zone }}."
    record_type: "{{ item.type | upper }}"
    record_name: "{{ item.name }}"
    record_value: '{{ item.data }}'
    validate_certs: "{{ ipa_validate_certs }}"
    state: present

...
