---

- name: Create dns zone {{ lan_domain }} @ {{ ipa_hostname }}
  community.general.ipa_dnszone:
    ipa_host: "{{ ipa_hostname }}"
    ipa_user: "{{ ipa_admin_user }}"
    ipa_pass: "{{ ipa_admin_password }}"
    zone_name: "{{ item }}"
    state: present
    validate_certs: "{{ ipa_validate_certs }}"
  loop: "{{ ipa_dns_zones }}"
  ignore_errors: true

- name: Add DNS records for hosts
  include_tasks: dns-hosts.yaml
  loop: "{{ lookup( 'ansible.builtin.dict', network_services ) }}"

- name: Create additional DNS entries
  include_tasks: dns-entries.yaml
  loop: "{{ ipa_dns_entries }}"

- name: Add SRV records
  include_tasks: dns-srv.yaml
  loop: "{{ ipa_srv_records }}"

- name: Add IPA groups
  include_tasks: add-groups.yaml
  loop: "{{ ipa_groups }}"

- name: Add IPA users
  include_tasks: add-users.yaml
  loop: "{{ ipa_users | subelements('groups') }}"

...