---
#
# wipe out the gpt partition information for a completely clean disk for ceph:
# sudo dd if=/dev/zero of=/dev/sda bs=512 count=34
#

# ceph_storage:
#   - name: w1.clt.milco.casa
#     devices:
#       - name: "nvme0n1"
#         osds: 1
#   - name: w2.clt.milco.casa
#     devices:
#       - name: "nvme0n1"
#         osds: 1
#   - name: w3.clt.milco.casa
#     devices:
#       - name: "nvme0n1"
#         osds: 1
