---

- name: Setup helm repo for MetalLB
  kubernetes.core.helm_repository:
    name: metallb
    url: https://metallb.github.io/metallb

- name: Install MetalLB
  kubernetes.core.helm:
    name: metallb
    chart_ref: metallb/metallb
    chart_version:
    namespace: metallb-system
    create_namespace: yes
    state: present

# FIXME: while this will kubectl apply manually,
# it's broken in ansible :(
- name: apply metallb config
  kubernetes.core.k8s:
    state: present
    template:
      - name: 'metallb-config.yaml.j2'

...