---

- name: Setup helm repo for MetalLB
  kubernetes.core.helm_repository:
    name: metallb
    url: https://metallb.github.io/metallb

- name: Install MetalLB
  kubernetes.core.helm:
    name: metallb
    chart_ref: metallb/metallb
    chart_version:
    namespace: "{{ metallb_namespace }}"
    create_namespace: yes
    state: present

- name: Wait for Metallb to be ready
  kubernetes.core.k8s_info:
    kind: Deployment
    wait: yes
    name: metallb-controller
    namespace: "{{ metallb_namespace }}"
    wait_sleep: 5
    wait_timeout: 360

- name: apply metallb config
  kubernetes.core.k8s:
    state: present
    template: 'metallb-config.yaml.j2'

...