---
apiVersion: v1
kind: Service
metadata:
  name: concourse-svc-ipv4
  namespace: "{{ concourse_namespace }}"
spec:
  selector:
    app: concourse-web
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  loadBalancerIP: "{{ servers.ci.ipv4 }}"
---
apiVersion: v1
kind: Service
metadata:
  name: concourse-svc-ipv6
  namespace: "{{ concourse_namespace }}"
spec:
  selector:
    app: concourse-web
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  loadBalancerIP: "{{ servers.ci.ipv6 }}"
