---

- name: configure the local workstation to run this ansible repo
  hosts: localhost
  tasks:
    - name: update software
      apt:
        name: "*"
        state: latest

    - name: install software common
      apt:
        name:
          - software-properties-common
          - python3-pip
        state: present
    - name: add ansible repo
      command: apt-add-repository --yes --update ppa:ansible/ansible

    - name: install applications
      apt:
        name:
          - ansible-base
          - sshpass
        state: latest

    - name: configure base system for ansible
      include_role:
        name: config-base

    - name: install ansible plugins via pip
      pip:
        name:
          - jenkins-job-builder
          - docker
