---

- name: Configure servers for use with ansible
  hosts: hosts
  become: no
  vars_files:
    - vaults/redhat.yml
  tasks:
    # TODO: why isn't the subscription command working from ansible?
    #    - name: setup red hat subscription
    #  redhat_subscription:
    #    username: "{{ redhat_username }}"
    #    password: "{{ redhat_password }}"
    #    auto_attach: yes
    #    state: present
    #  when: ansible_distribution == "RedHat"
    - name: install python
      raw: "yum install -y python3"
    - name: add ansible user
      user:
        name: "{{ ansible_user }}"
        state: present
    - name: add ssh pub key
      authorized_key:
        user: "{{ ansible_user }}"
        key: "{{ lookup( 'file', '~/.ssh/id_rsa.pub' ) }}"
        state: present
    - name: configure sudo
      copy:
        content: "{{ ansible_user }} ALL=(ALL) NOPASSWD: ALL"
        dest: /etc/sudoers.d/{{ ansible_user }}
        validate: 'visudo -cf %s'
    - name: update all packages
      yum:
        name: "*"
        state: latest
    - name: test ansible configuration
      ping:
