---

- name: configure a workstation for personal use
  hosts: "{{ workstation }}"
  vars_prompt:
    - name: workstation
      prompt: "Workstation to configure?"
      default: "localhost"
      private: no
  tasks:
    - name: install VS Code
      apt:
        deb: https://go.microsoft.com/fwlink/?LinkID=760868
        state: present

    - name: install Manuskript
      apt:
        deb: https://github.com/olivierkes/manuskript/releases/download/0.12.0/manuskript-0.12.0-1.deb
        state: present

    - name: install MongoDB Compass
      apt:
        deb: https://downloads.mongodb.com/compass/mongodb-compass_1.28.1_amd64.deb
        state: present

    - name: install SpiderOakOne
      apt:
        deb: https://spideroak.com/release/spideroak/deb_x64
        state: present

    - name: add 32bit arch for adding wine pkgs
      lineinfile:
        dest: /var/lib/dpkg/arch
        line: "i386"
        create: yes
      register: add_i386
    - name: Add wine key to apt
      apt_key:
        url: https://dl.winehq.org/wine-builds/winehq.key
        keyring: /etc/apt/trusted.gpg.d/wine.gpg
        state: present
    - name: Add wine repo
      ansible.builtin.apt_repository:
        repo: deb https://dl.winehq.org/wine-builds/ubuntu/ hirsute main
        state: present

    - name: Add signal apt key
      apt_key:
        url: https://updates.signal.org/desktop/apt/keys.asc
        keyring: /usr/share/keyrings/signal-desktop-keyring.gpg
        state: present
    - name: Add signal repo
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64 signed-by=/usr/share/keyrings/signal-desktop-keyring.gpg] https://updates.signal.org/desktop/apt xenial main
        state: present

    - name: Add k8s key to apt
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        keyring: /etc/apt/trusted.gpg.d/google-k8s.gpg
        state: present
    - name: Add k8s repo
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/etc/apt/trusted.gpg.d/google-k8s.gpg] https://apt.kubernetes.io/ kubernetes-xenial main
        state: present

    - name: Add an Apt signing key to a specific keyring file
      apt_key:
        url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
        keyring: /etc/apt/trusted.gpg.d/brave-browser.gpg
        state: present
    - name: create repo for brave
      copy:
        content: "deb [signed-by=/etc/apt/trusted.gpg.d/brave-browser.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main"
        dest: /etc/apt/sources.list.d/brave-browser-release.list

    - name: add kubuntu backports repo
      command: apt-add-repository --yes --update ppa:kubuntu-ppa/backports

    - name: install software common
      apt:
        name:
          - apt-transport-https
          - autofs
          - basket
          - brave-browser
          - chromium-browser
          - duplicati
          - duplicity
          - firefox
          - giggle
          - gimp
          - inkscape
          - kdenlive
          - kompare
          - krita
          - kubectl
          - mkvtoolnix-gui
          - mplayer
          - ohcount
          - retext
          - signal-desktop
          - sloccount
          - tldr
          - virtualbox
          - virt-manager
          - vlc
          - yakuake
          - winbind
#          - winehq-stable

        state: present

    - name: Install snaps
      community.general.snap:
        name:
          - atom
          - spotify
        classic: yes

    - name: update kubuntu
      apt:
        name: "*"
        update_cache: "{{ add_i386.changed }}"
        state: latest

    - name: enable auto.misc
      lineinfile:
        path: /etc/auto.master
        regexp: '#/misc'
        line: '/misc        /etc/auto.misc'

    - name: add shares
      template:
        src: auto.misc
        dest: /etc/auto.misc
        owner: root
        group: root
        mode: '0644'

    - name: restart autofs
      service:
        name: autofs
        state: restarted
        enabled: true
