---

- name: configure a workstation for running playbooks
  hosts: "workstations"
  connection: local
  tasks:
    - name: Add k8s key to apt
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        keyring: /etc/apt/trusted.gpg.d/google-k8s.gpg
        state: present
    - name: Add k8s repo
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/etc/apt/trusted.gpg.d/google-k8s.gpg] https://apt.kubernetes.io/ kubernetes-xenial main
        state: present

    - name: install software common
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - htop
          - flatpak
          - podman
          - python3
          - python3-pip
          - tmux
          - vim
        state: present

    - name: set default cli editor
      community.general.alternatives:
        name: editor
        path: /usr/bin/vim.basic

    - name: download kubectl
      ansible.builtin.uri:
        url: https://dl.k8s.io/release/v1.27.3/bin/linux/amd64/kubectl
        dest: "$HOME/.local/bin/kubectl"
        mode: 0755
        status_code: [200,304]
      become: no

    - name: install pip packages
      ansible.builtin.pip:
        name:
          - pre-commit
