---

- name: configure a workstation for personal use
  hosts: "workstations"
  connection: local
  become: false
  tasks:
    - name: add kubuntu backports repo
      command: apt-add-repository --yes --update ppa:kubuntu-ppa/backports
      when: ansible_distribution == 'Ubuntu'
      become: yes
      tags:
        - backports

    - name: install ProtonVPN repo
      ansible.builtin.apt:
        deb: https://repo.protonvpn.com/debian/dists/stable/main/binary-all/protonvpn-stable-release_1.0.3-2_all.deb
      become: yes
      tags:
        - proton
    - name: install proton vpn
      ansible.builtin.apt:
        name:
          - protonvpn
        update_cache: yes
      become: yes
      tags:
        - proton

    - name: install tabby console
      ansible.builtin.apt:
        deb: https://github.com/Eugeny/tabby/releases/download/v1.0.197/tabby-1.0.197-linux-x64.deb
      become: yes
      tags:
        - tabby

    - name: install balena
      ansible.builtin.apt:
        deb: https://github.com/balena-io/etcher/releases/download/v1.18.4/balena-etcher_1.18.4_amd64.deb
      become: yes
      tags:
        - balena

    - name: install dev apps
      ansible.builtin.apt:
        name:
          - giggle
          - kompare
          - ohcount
          - openconnect
          - qgit
          - retext
          - sloccount
          - tldr
          - yakuake
        state: present
      become: yes
      tags:
        - dev-tools

    - name: install random apps
      ansible.builtin.apt:
        name:
          - autokey-qt
          - basket
          - konqueror
          - neovim-qt
          - skanlite
          - virt-manager
      become: yes
      tags:
        - other-apps

    - name: install work flatpak apps
      community.general.flatpak:
        name:
          - app/org.apache.directory.studio
          - app/brave
          - app/org.gnome.Evolution
          - app/gimp
          - git-cola
          - gitg
          - gittyup
          - iplookup
          - kcalc
          - app/libreoffice
          - librewolf
          - mattermost
          - meld
          - app/obsidian
          - openlens
          - podmandesktop
          - postman
          - retext
          - signal
          - vscodium
        state: present
      tags:
        - work

    - name: install non-work flatpak apps
      community.general.flatpak:
        name:
          - bibletime
          - app/bitwarden
          - app/org.chromium.chromium/x86_64/stable
          - app/com.dosbox.dosbox
          - app/org.mozilla.firefox/x86_64/stable
          - app/handbrake
          - inkscape
          - jitsi
          - kdenlive
          - app/krita
          - lapce
          - manuskript
          - mkvtoolnix-gui
          - neovim
          - app/org.nextcloud.nextcloud
          - scribus
          - simplenote
          - slack
          - spotify
          - sweethome3d
          - app/org.videolan.VLC
          - xiphos
          - com.yubico.yubioath
        state: present
      tags:
        - personal

    - name: update os
      ansible.builtin.apt:
        name: "*"
        state: latest
      become: yes
      tags:
        - updates
