---

- name: configure a workstation for running playbooks
  hosts: "workstations"
  connection: local
  tasks:
    - name: Add k8s key to apt
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        keyring: /etc/apt/trusted.gpg.d/google-k8s.gpg
        state: present
    - name: Add k8s repo
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/etc/apt/trusted.gpg.d/google-k8s.gpg] https://apt.kubernetes.io/ kubernetes-xenial main
        state: present

    - name: install software common
      ansible.builtin.apt:
        name:
          - htop
          - python3
          - python3-pip
          - apt-transport-https
          - flatpak
          - kubectl
          - tmux
          - vim
        state: present

    - name: install pip packages
      ansible.builtin.pip:
        name:
          - pre-commit
