---
- name: configure master node
  hosts: k8smasters
  tags:
    - config_system
    - config_k8s_master
  tasks:
    - name: configure worker nodes
      include_role:
        name: config-base

- name: configure base systems
  hosts: k8sworkers
  remote_user: rock64
  tags:
    - config_system
    - config_k8s_nodes
  tasks:
    - name: configure base
      include_role:
        name: config-base

- name: configure master node
  hosts: k8smasters
  tags:
    - config_k8s
    - config_k8s_master
  tasks:
    - name: include docker role
      include_role:
        name: docker
    - name: include kubernetes
      include_role:
        name: kubernetes
    - name: include calico role
      include_role:
        name: calico

# Service.spec.ipFamilyPolicy: SingleStack, PreferDualStack, RequireDualStack
# ipFamilies:
#   - IPv6
#   - IPv4

- name: configure worker nodes
  hosts: k8sworkers
  tags:
    - config_k8s
    - config_k8s_nodes
  remote_user: rock64
  tasks:
    - name: upload join script
      copy:
        src: /tmp/join_node.sh
        dest: /root/join_node.sh
        owner: root
        group: root
        mode: '0755'
    - name: join cluster
      command: /root/join_node.sh
    - name: enable start kubelet
      service:
        name: kubelet
        state: started
        enabled: yes

- name: test nodes joined
  hosts: k8smasters
  tags:
    - config_k8s
    - check_nodes
  tasks:
    - name: check for nodes
      command: kubectl get nodes
