---

- name: Setup DNS
  hosts: router
  gather_facts: false
  remote_user: root
  tags:
    - never
    - dns
  roles:
    - role: openwrt

- name: Configure base OS
  hosts: metal
  tags:
    - controllers
    - workers
  roles:
    - role: configure-os

- name: Setup backups
  hosts: backups
  tags:
    - backups
  roles:
    - role: backups

- name: configure master node
  hosts: controllers
  tags:
    - cluster
  roles:
    - role: containerd
      tags:
        - containerd
    - role: kubernetes
      tags:
        - k8s
    # - role: cilium
    # - role: metallb

...