---

- name: Setup DNS
  hosts: router
  gather_facts: false
  remote_user: root
  tags:
    - never
    - dns
  roles:
    - role: openwrt

- name: Configure base OS
  hosts: metal
  tags:
    - controllers
    - workers
  roles:
    - role: configure-os

- name: Setup backups
  hosts: backups
  tags:
    - backups
  roles:
    - role: backups

- name: configure node
  hosts:
    - controllers
    - workers
  tags:
    - cluster
  roles:
    - role: containerd
      tags:
        - containerd
    - role: crio
      tags:
        - never
        - crio
    - role: kubernetes
      tags:
        - k8s

- name: Install Helm
  hosts:
    - controllers
  tags:
    - cluster
    - tools
    - helm
  roles:
    - role: helm

- name: configure CNI
  hosts:
    - controllers
  tags:
    - cluster
    - cni
    - cilium
  roles:
    - role: cilium


    # - role: metallb

...