---

- name: Setup DNS
  hosts: router
  gather_facts: false
  remote_user: root
  tags:
    - never
    - dns
  roles:
    - role: openwrt

- name: Configure base OS
  hosts: metal
  tags:
    - controllers
    - workers
  roles:
    - role: configure-os

- name: Setup backups
  hosts: backups
  tags:
    - backups
  roles:
    - role: backups

- name: configure node
  hosts:
    - controllers
    - workers
  tags:
    - cluster
    - runtime
  roles:
    - role: containerd
      when: k8s_runtime == 'containerd'
    - role: crio
      when: k8s_runtime == 'crio'
    - role: kubernetes
      tags:
        - k8s

- name: Install Helm
  hosts:
    - controllers
  tags:
    - cluster
    - helm
  roles:
    - role: helm

- name: configure CNI
  hosts:
    - controllers
  tags:
    - cluster
    - cni
  roles:
    - role: cilium
      when: k8s_cni == 'cilium'

- name: deploy the load balanacer
  hosts:
    - controllers
  tags:
    - lb
    - metallb
  roles:
    - role: metallb

- name: Wipe ceph drives
  hosts:
    - controllers
  tags:
    - never
    - yes-really-wipe-the-ceph-drives
  tasks:
    - include_tasks: roles/rook/tasks/format-disks.yaml

- name: Deploy Rook ceph
  hosts:
    - controllers
  tags:
    - storage
    - rook
    - ceph
  roles:
    - role: rook

- name: Deploy ingress-nginx
  hosts:
    - ingress
  tags:
    - apps
    - ingress
  roles:
    - role: ingress-nginx
      when: "'ingress-nginx' in ingress_controllers"

- name: Deploy Free IPA
  hosts:
    - freeipa
  tags:
    - apps
    - ipa
  roles:
    - role: freeipa

- name: Deploy gitea
  hosts:
    - gitea
  tags:
    - apps
    - gitea
  roles:
    - role: gitea


...