
- name: erase drives
  command: "sgdisk -Z /dev/{{ item.1.name }}"
  delegate_to: "{{ item.0.name }}"
  with_subelements:
    - "{{ ceph_storage }}"
    - devices

- name: delete rook configuration folder
  file:
    path: "/var/lib/rook"
    state: absent

