---

- name: install lvm2 and other fs tools
  apt:
    name:
      - lvm2
      - xfsprogs
      - hdparm
    state: present

- name: Label node as storage node
  kubernetes.core.k8s:
    state: present
    definition:
      apiversion: v1
      kind: Node
      metadata:
        name: "{{ ansible_hostname }}"
        label:
          "{{ lan_tld }}/node-role": "storage-node"

- name: Add rook helm repo
  kubernetes.core.helm_repository:
    name: rook-release
    url: https://charts.rook.io/release
    state: present

- name: Deploy Rook Operator Helm chart
  kubernetes.core.helm:
    name: rook-ceph
    kubeconfig: /etc/kubernetes/admin.conf
    chart_ref: rook-release/rook-ceph
    chart_version: "{{ rook_version }}"
    namespace: "{{ rook_namespace }}"
    create_namespace: true
    values: "{{ lookup('template', 'rook-values.yaml.j2') | from_yaml }}"
    state: present

- name: Deploy Rook Cluster Helm chart
  kubernetes.core.helm:
    name: rook-ceph-cluster
    kubeconfig: /etc/kubernetes/admin.conf
    chart_ref: rook-release/rook-ceph-cluser
    chart_version: "{{ rook_version }}"
    namespace: "{{ rook_namespace }}"
    values: "{{ lookup('template', 'rook-cluster-values.yaml.j2') | from_yaml }}"
    state: present

- name: Deploy LoadBalancer for public s3 endpoint
  kubernetes.core.k8s:
    state: present
    template: 's3.yaml.j2'
...
