---

- name: install lvm2
  apt:
    name:
      - lvm2
      - xfsprogs
    state: present

- name: Add rook helm repo
  kubernetes.core.helm_repository:
    name: rook-release
    url: https://charts.rook.io/release

- name: Deploy Rook Operator Helm chart
  kubernetes.core.helm:
    name: rook-ceph
    namespace: rook-ceph
    chart_ref: rook-release/rook-ceph
    chart_version: "{{ rook_ceph_version }}"
    create_namespace: true
    #values: "{{ lookup('template', 'rook-values.yaml.j2') | from_yaml }}"

# - name: create rook ceph server & tools
#   kubernetes.core.k8s:
#     state: present
#     template: "{{ item }}"
#   loop:
#     - rook-ceph.yml
#     - rook-tools.yml
...
