---

- name: setup red hat subscription
  redhat_subscription:
    username: "{{ redhat_username }}"
    password: "{{ redhat_password }}"
    auto_attach: yes
    consumer_id: "{{ redhat_system_uuid }}"
    state: present
  when: ansible_distribution == "RedHat"

- name: install python
  package:
    name: python3
    state: latest

- name: set hostname
  hostname:
    name: "{{ inventory_hostname }}.{{ lan_domain }}"
  when: inventory_hostname != "localhost"

- name: add ansible user
  user:
    name: "{{ preferred_ansible_user }}"
    shell: /bin/bash
    state: present
- name: add ssh pub key
  authorized_key:
    user: "{{ preferred_ansible_user }}"
    key: "{{ lookup( 'file', '~/.ssh/id_rsa.pub' ) }}"
    state: present
- name: configure sudo
  copy:
    content: "{{ preferred_ansible_user }} ALL=(ALL) NOPASSWD: ALL"
    dest: /etc/sudoers.d/{{ preferred_ansible_user }}
    validate: 'visudo -cf %s'

- name: set the timezone
  timezone:
    name: "America/Los_Angeles"

- name: install virtualization packages
  yum:
    name:
      - "@Virtualization Host"
      - libguestfs-tools
    state: present
  when: ansible_distribution == "RedHat"

# we just installed all the virtualization packages
# but we need a user to access it
- name: add libvirt group
  user:
    name: "{{ ansible_user }}"
    append: yes
    groups: libvirt
  when: ansible_os_family == "RedHat"

- name: start/enable libvirtd
  service:
    name: libvirtd
    state: started
    enabled: yes


- name: update all packages
  package:
    name: "*"
    state: latest

- name: test ansible configuration
  ping:
