---
# tasks file for metallb

- name: Download metallb namespace
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/metallb/metallb/v{{ metallb_version }}/manifests/namespace.yaml
    dest: ~/namespace.yaml
    mode: '0644'

- name: Download metallb objects
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/metallb/metallb/v{{ metallb_version }}/manifests/metallb.yaml
    dest: ~/metallb.yaml
    mode: '0644'

- name: install namespace
  kubernetes.core.k8s:
    state: present
    src: ~/namespace.yaml

- name: install metallb objects
  kubernetes.core.k8s:
    state: present
    src: ~/metallb.yaml

- name: create random key
  command: openssl rand -base64 128
  register: key

- name: create secret key
  command: kubectl create secret generic -n metallb-system memberlist --from-literal=secretkey="{{ key.stdout_lines | join('') }}"

- name: apply metallb config
  kubernetes.core.k8s:
    state: present
    template: 'metallb-config.yml'
