---

all:
  children:
    metal:
      children:
        controllers:
          hosts:
            c1.clt.milco.casa:
        workers:
          hosts:
            w1.clt.milco.casa:
            w2.clt.milco.casa:
    openwrt:
      children:
        router:
          hosts:
            r.milco.casa:

backups:
  hosts:
    c1.clt.milco.casa:
