---
# tasks file for purelb

- name: get purelb install config
  uri:
    url: https://gitlab.com/purelb/purelb/-/raw/main/deployments/purelb-complete.yaml
    dest: /home/{{ ansible_user }}/purelb-complete.yaml

- name: create loadbalancer
  become: no
  command: kubectl create -f /home/{{ ansible_user }}/purelb-complete.yaml
  ignore_errors: yes
  
- name: create ip pool for load balancer
  template:
    src: purelb-pool.yml.j2
    dest: /home/{{ ansible_user }}/purelb-pool.yml
- name: create ip address pool
  become: no
  command: kubectl create -f /home/{{ ansible_user }}/purelb-pool.yml
