---
# tasks file for istio

- name: create istio namespace
  become: no
  command: kubectl create namespace {{ istio_namespace }}

- name: download istio downloader
  uri:
    url: https://istio.io/downloadIstio
    dest: /home/{{ ansible_user }}/downloadIstio
    mode: '0700'
    status_code:
      - 200
      - 304

- name: download our version of istio
  uri:
    url: https://github.com/istio/istio/releases/download/{{ istio_version }}/istio-{{ istio_version }}-Linux-amd64.tar.gz
    dest: /home/{{ ansible_user }}/istio-{{ istio_version }}-Linux-amd64.tar.gz
    status_code:
      - 200
      - 304

- name: unarchive istio
  unarchive:
    src:  /home/{{ ansible_user }}/istio-{{ istio_version }}-Linux-amd64.tar.gz
    dest: /home/{{ ansible_user }}/
    remote_src: yes
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: install base istio features
  become: no
  command: helm install istio-base /home/{{ ansible_user }}/istio-{{ istio_version }}/manifests/charts/base -n {{ istio_namespace }}

- name: install istiod service
  become: no
  command: helm install istiod /home/{{ ansible_user }}/istio-{{ istio_version }}/manifests/charts/istio-control/istio-discovery -n {{ istio_namespace }}

# - name: install istio ingress
#   become: no
#   command: helm install istio-ingress /home/{{ ansible_user }}/istio-{{ istio_version }}/manifests/charts/gateways/istio-ingress -n {{ istio_namespace }}
#
# - name: install istio egress
#   become: no
#   command: helm install istio-egress /home/{{ ansible_user }}/istio-{{ istio_version }}/manifests/charts/gateways/istio-egress -n {{ istio_namespace }}
