---

- name: Create dns zone {{ lan_domain }} @ {{ ipa_hostname }}
  community.general.ipa_dnszone:
    ipa_host: "{{ ipa_hostname }}"
    ipa_user: "{{ ipa_admin_user }}"
    ipa_pass: "{{ ipa_admin_password }}"
    zone_name: "{{ lan_domain }}."
    state: present
    validate_certs: false
  ignore_errors: true

- name: Add DNS records
  include_tasks: dns-entries.yaml
  loop: "{{ lookup( 'ansible.builtin.dict', network_services ) }}"

- name: Add IPA groups
  include_tasks: add-groups.yaml
  loop: "{{ ipa_groups }}"

- name: Add IPA users
  include_tasks: add-users.yaml
  loop: "{{ ipa_users|subelements('groups') }}"

...