
- name: create temp folder
  ansible.builtin.tempfile:
    state: directory
  register: tempfolder

- name: create dest folder
  ansible.builtin.file:
    path: /usr/local/bin/
    owner: root
    group: root
    mode: 0755
    state: directory

- name: download files
  ansible.builtin.get_url:
    url: https://github.com/cilium/cilium-cli/releases/download/v{{ cilium_version }}/cilium-linux-amd64.tar.gz
    dest: "{{ tempfolder.path }}/"
    checksum: "sha256:https://github.com/cilium/cilium-cli/releases/download/v{{ cilium_version }}/cilium-linux-amd64.tar.gz.sha256sum"

- name: unarchive files
  ansible.builtin.unarchive:
    src: "{{ tempfolder.path }}/cilium-linux-amd64.tar.gz"
    remote_src: true
    dest: "/usr/local/bin"
    owner: root
    group: root
    mode: 0755

- name: install cilium
  become: yes
  ansible.builtin.command:
    cmd: cilium install