---
#
# sudo ubuntu-drivers autoinstall

- name: install nvidia drivers
  ansible.builtin.command:
    cmd: ubuntu-drivers autoinstall
  become: true

- name: Label node as nvidia node
  ansible.builtin.command:
    cmd: "kubectl label node {{ inventory_hostname }} {{ lan_domain }}/node-hardware=nvidia-gpu"
  delegate_to: "{{ k8s_controller }}"
...