---
# defaults file for jenkins

jenkins_data_path: "{{ pod_data_path }}/jenkins"

jenkins_base_url: "http://ci.{{ lan_domain }}"

# Path for the Configuration as Code yaml file
jenkins_casc_path: /usr/share/jenkins/casc/

jenkins_plugins: []

jenkins_agent_basename: worker
jenkins_agent_default_image: jenkins/jnlp-agent-alpine
jenkins_agent_workdir: /home/jenkins/agent
jenkins_agent_labels: docker
jenkins_agent_slave_port: 50000

k8s_jenkins_namespace: jenkins
