---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: git-repos
  namespace: {{ gitea_namespace }}
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-database
  namespace: {{ gitea_namespace }}
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: gitea
#   name: gitea-lb
#   namespace: {{ gitea_namespace }}
# spec:
#   type: LoadBalancer
#   loadBalancerIP: {{ servers.git.ipv4 }}
#   ipFamilyPolicy: SingleStack
#   ipFamilies:
#     - IPv4
#   externalTrafficPolicy: Local
#   ports:
#   - name: ssh
#     port: 22
#     protocol: TCP
#     targetPort: 22
#   - name: http
#     port: 80
#     protocol: TCP
#     targetPort: 3000
#   selector:
#     app: gitea
#   sessionAffinity: None
