apiVersion: v1
kind: Namespace
metadata:
  name: {{ gitea_namespace }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: git-repos
  namespace: {{ gitea_namespace }}
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-database
  namespace: {{ gitea_namespace }}
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: Secret
metadata:
  name: gitea-secret
  namespace: {{ gitea_namespace }}
data:
  MYSQL_ROOT_PASSWORD: "{{ vault_MYSQL_ROOT_PASSWORD | b64encode }}"
  MYSQL_DATABASE: "{{ vault_MYSQL_DATABASE | b64encode }}"
  MYSQL_USER: "{{ vault_MYSQL_USER | b64encode }}"
  MYSQL_PASSWORD: "{{ vault_MYSQL_PASSWORD | b64encode }}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
  name: db
  namespace: {{ gitea_namespace }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - image: mariadb:10
        name: db
        volumeMounts:
          - name: mysql-data
            mountPath: /var/lib/mysql
        ports:
          - containerPort: 3306
            name: mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: gitea-secret
                key: MYSQL_ROOT_PASSWORD
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: gitea-secret
                key: MYSQL_DATABASE
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: gitea-secret
                key: MYSQL_USER
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: gitea-secret
                key: MYSQL_PASSWORD
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: gitea-database
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gitea
  name: gitea
  namespace: {{ gitea_namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
        - image: gitea/gitea:{{ gitea_version }}
          name: gitea
          env:
            - name: DB_TYPE
              value: mysql
            - name: DB_HOST
              value: db-svc:3306
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: gitea-secret
                  key: MYSQL_DATABASE
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: gitea-secret
                  key: MYSQL_USER
            - name: DB_PASSWD
              valueFrom:
                secretKeyRef:
                  name: gitea-secret
                  key: MYSQL_PASSWORD
            - name: DOMAIN
              value: "git.{{ lan_domain }}"
            - name: REQUIRE_SIGNIN_VIEW
              value: "true"
            - name: LFS_START_SERVER
              value: "true"
            - name: PROTOCOL
              value: "http"
            - name: APP_NAME
              value: "{{ gitea_app_name }}"
            - name: RUN_MODE
              value: "{{ gitea_run_mode }}"
            - name: ROOT_URL
              value: "http://git.{{ lan_domain }}"
          volumeMounts:
            - name: repository
              mountPath: /data
            - name: timezone
              mountPath: /etc/timezone
              readOnly: true
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true
      initContainers:
        - image: busybox
          name: test-nfs
          command: ['sh', '-c', "until nc -zv rook-nfs.rook-nfs.svc.cluster.local 2049; do echo waiting for nfs; sleep 2; done"]
        - image: busybox
          name: test-db
          command: ['sh', '-c', "until nslookup db-svc.gitea.svc.cluster.local; do echo waiting for db; sleep 2; done"]
      volumes:
        - name: repository
          persistentVolumeClaim:
            claimName: git-repos
        - name: timezone
          hostPath:
            path: /etc/timezone
        - name: localtime
          hostPath:
            path: /etc/localtime
---
apiVersion: v1
kind: Service
metadata:
  name: db-svc
  namespace: {{ gitea_namespace }}
spec:
  type: ClusterIP
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gitea
  name: gitea-lb
  namespace: {{ gitea_namespace }}
spec:
  type: LoadBalancer
  loadBalancerIP: {{ servers.git.ipv4 }}
  ipFamilyPolicy: SingleStack
  ipFamilies:
    - IPv4
  externalTrafficPolicy: Local
  ports:
  - name: ssh
    port: 22
    protocol: TCP
    targetPort: 22
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: gitea
  sessionAffinity: None
