---
# tasks file for nfs

- name: create path for exports
  file:
    path: "{{ nfs_config_path }}/"
    recurse: yes
    state: directory
    owner: root
    group: root
    mode: '0640'

- name: generate exports file
  tags:
    - update_exports
  template:
    src: exports.j2
    dest: "{{ nfs_config_path }}/exports"
- name: generate krb5.conf file
  tags:
    - update_exports
  template:
    src: krb5.conf.j2
    dest: "{{ nfs_config_path }}/krb5.conf"
- name: get nfs pod name
  become: no
  tags:
    - never
    - update_exports
  command: kubectl -n nfs get pods -o jsonpath='{.items[].metadata.name}'
  register: podname
- name: force nfs to update shares
  become: no
  tags:
    - never
    - update_exports
  command: kubectl -n nfs exec -it {{ podname.stdout }} -- exportfs -ra
  when: podname.stdout is defined

- name: copy nfs yaml files to server
  template:
    src: "nfs.yml.j2"
    dest: /home/{{ ansible_user }}/nfs.yml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: create nfs deployments and services
  become: no
  command: kubectl apply -f /home/{{ ansible_user }}/nfs.yml
