---
# tasks file for nfs

- name: create path for exports
  file:
    path: "{{ nfs_config_path }}/"
    recurse: yes
    state: directory
    owner: root
    group: root
    mode: '0640'
- name: generate exports file
  tags:
    - update_exports
  template:
    src: exports.j2
    dest: "{{ nfs_config_path }}/exports"
- name: get nfs pod name
  tags:
    - never
    - update_exports
  command: kubectl -n nfs get pods -o jsonpath='{.items[].metadata.name}'
  register: podname
- name: force nfs to update shares
  tags:
    - never
    - update_exports
  command: kubectl -n nfs exec -it {{ podname.stdout }} -- exportfs -ra
  when: podname.stdout is defined

- name: copy nfs yaml files to server
  template:
    src: "{{ item }}.j2"
    dest: /home/{{ ansible_user }}/{{ item }}.yml
  loop: "{{ nfs_config_files }}"

- name: create nfs deployments and services
  command: kubectl create -f /home/{{ ansible_user }}/{{ item }}.yml
  loop: "{{ nfs_config_files }}"
  register: create_unit
  ignore_errors: yes
  changed_when:
    - '"AlreadyExists" in create_unit.stdout'
