apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-robot
  namespace: {{ k8s_jenkins_namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-robot
  namespace: {{ k8s_jenkins_namespace }}
  labels:
    "app.kubernetes.io/name": 'jenkins'
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec", "pods/log", "persistentvolumeclaims", "events"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods", "pods/exec", "persistentvolumeclaims", "events"]
  verbs: ["create", "apply", "delete", "deletecollection", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-robot-binding
  namespace: {{ k8s_jenkins_namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins-robot
subjects:
- kind: ServiceAccount
  name: jenkins-robot
  namespace: {{ k8s_jenkins_namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-robot-global
  namespace: {{ k8s_jenkins_namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jenkins-robot-global
  namespace: {{ k8s_jenkins_namespace }}
  labels:
    "app.kubernetes.io/name": 'jenkins'
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec", "pods/log", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods", "pods/exec", "persistentvolumeclaims"]
  verbs: ["create", "apply", "delete", "deletecollection", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-robot-global-binding
  namespace: {{ k8s_jenkins_namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jenkins-robot-global
subjects:
- kind: ServiceAccount
  name: jenkins-robot-global
  namespace: {{ k8s_jenkins_namespace }}
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-jnlp
  namespace: {{ k8s_jenkins_namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 50000
      targetPort: 50000
  selector:
    app: jenkins
  ipFamilyPolicy: RequireDualStack
  ipFamilies:
    - IPv6
    - IPv4
