---
# tasks file for kubernetes master

- name: populate service facts
  service_facts:

- name: install apt packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
    state: present

- name: Download k8s gpg keys
  ansible.builtin.uri:
    url: https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version[:-2] }}/deb/Release.key
    dest: /etc/apt/trusted.gpg.d/kubernetes-apt-keyring.asc
    status_code:
      - 200
      - 304

- name: Configure k8s repo
  ansible.builtin.blockinfile:
    path: /etc/apt/sources.list.d/kubernetes.list
    block: |
      deb [signed-by=/etc/apt/trusted.gpg.d/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version[:-2] }}/deb/ /
    create: yes
    state: present

- name: install kubectl kubeadm and kubelet
  ansible.builtin.apt:
    name:
      - kubeadm={{ kubernetes_version }}-1.1
      - kubectl={{ kubernetes_version }}-1.1
      - kubelet={{ kubernetes_version }}-1.1
    allow_change_held_packages: yes
    state: present
    update_cache: yes

- name: mark hold updates on k8s packages
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubeadm
    - kubectl
    - kubelet
#
# If the firewall is enabled you may see the following issue:
# Everything in the cluster looks like it's working, but you cannot
# connect to services backed by pods, or the pods themselves on the
# node(s) with the firewall running.
#
- name: disable firewall
  ansible.builtin.service:
    name: ufw
    state: stopped
    enabled: no
  when: "'ufw' in ansible_facts.services"
