---
# tasks file for kubernetes master

- name: populate service facts
  service_facts:

- name: install apt packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
    state: present

- name: Download kubectl binary
  ansible.builtin.get_url:
    url: "https://dl.k8s.io/release/v{{ kubernetes_version }}/bin/linux/amd64/kubectl"
    dest: /usr/local/bin/kubectl
    owner: root
    group: root
    mode: 0755
    checksum: sha256:https://dl.k8s.io/release/v{{ kubernetes_version }}/bin/linux/amd64/kubectl.sha256

- name: Donwload kubeadm binary
  ansible.builtin.get_url:
    url: https://dl.k8s.io/release/v{{ kubernetes_version }}/bin/linux/amd64/kubeadm
    dest: /usr/local/bin/kubeadm
    owner: root
    group: root
    mode: 0755
    checksum: sha256:https://dl.k8s.io/release/v{{ kubernetes_version }}/bin/linux/amd64/kubeadm.sha256

- name: Donwload kubelete binary
  ansible.builtin.get_url:
    url: https://dl.k8s.io/release/v{{ kubernetes_version }}/bin/linux/amd64/kubelet
    dest: /usr/local/bin/kubelet
    owner: root
    group: root
    mode: 0755
    checksum: sha256:https://dl.k8s.io/release/v{{ kubernetes_version }}/bin/linux/amd64/kubelet.sha256

#
# If the firewall is enabled you may see the following issue:
# Everything in the cluster looks like it's working, but you cannot
# connect to services backed by pods, or the pods themselves on the
# node(s) with the firewall running.
#
- name: disable firewall
  ansible.builtin.service:
    name: ufw
    state: stopped
    enabled: no
  when: "'ufw' in ansible_facts.services"
