---

- name: master node setup
  import_tasks: server.yml
  when:
    - ansible_os_family == "RedHat"
    - role_type == "master"

- name: worker node setup
  import_tasks: worker.yml
  when:
    - ansible_os_family == "Debian"
    - role_type == "worker"
