---

- name: create kubeadm init config
  template:
    src: kubeadm.yaml
    dest: /root/kubeadm.yaml

- name: kubeadm init
  command: kubeadm init --config /root/kubeadm.yaml

- name: create .kube config dir
  file:
    path: "/home/{{ ansible_user }}/.kube"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: copy k8 config to user dir
  copy:
    remote_src: yes
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{ ansible_user }}/.kube/config"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: untaint master node so it can run pods
  become: no
  command: kubectl taint node {{ k8s_command_node }} node-role.kubernetes.io/master:NoSchedule-
  when: k8s_master_can_run_pods
