---

- name: create kubeadm init config
  template:
    src: kubeadm.yaml.j2
    dest: /root/kubeadm.yaml

- name: kubeadm init
  command: kubeadm init --config /root/kubeadm.yaml

- name: create .kube config dir
  file:
    path: "/home/{{ ansible_user }}/.kube"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: copy k8 config to user dir
  copy:
    remote_src: yes
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{ ansible_user }}/.kube/config"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
