---

- name: Create namespace
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ ipa_namespace }}"
    state: present

# TODO: test for PVC before deploying it again
# - name: Test for PVC
#   ansible.builtin.command:
#     cmd: kubectl -n {{ ipa_namespace }}

- name: Deploy IPA PVC
  kubernetes.core.k8s:
    state: present
    template: 'freeipa-pvc.yaml.j2'

- name: Create IPA Secrets
  kubernetes.core.k8s:
    state: present
    template: 'freeipa-secret.yaml.j2'

- name: Deploy IPA StatefulSet
  kubernetes.core.k8s:
    state: present
    template: 'freeipa-statefulset.yaml.j2'

- name: Deploy IPA Services
  kubernetes.core.k8s:
    state: present
    template: 'freeipa-svc.yaml.j2'

...
