---

nfs_storage_host: k8sm.milco.info

nfs_config_path: "{{ pod_config_base_path }}/nfs"

#
# --tags update_exports
# This breaks the file link into the pod and it has to be recreated.
# For production create a custom image with a soft link to the
# exports file so it updates automatically.
#
nfs_exports:
- share: /srv/shares
  hosts:
    - name: "*"
      options:
        - "rw"
        - "sync"
        - "no_root_squash"
        - "insecure"
- share: /srv/_installers
  hosts:
    - name: "*"
      options:
        - "rw"
        - "sync"
        - "no_root_squash"
        - "insecure"
