---
# tasks file for jenkins
#

- name: create folder
  file:
    path: "{{ pod_data_path }}/jenkins"
    state: directory

- name: copy in config file
  template: "{{ item }}"
    src: jenkins.yml
    dest: /home/{{ ansible_user }}/{{ item }}
  loop: "{{ k8s_jenkins_config }}"

- name: deploy jenkins
  become: no
  command: kubectl apply -f /home/{{ ansible_user }}/{{ item }}
  loop: "{{ k8s_jenkins_config }}"
