---

ipa_groups:
  - k8s_admins
  - developers
  - users

ipa_users:
  - name: brian.milco
    givenname: Brian
    surname: Milco
    email:
      - brian@milco.info
      - bcmilco@gmail.com
    sshkeys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDD2LgGJ9phE2R9zosHKQO9UuNgK9NnC1lJMER7VVWgo90ESs73PZL70Ia8cj43Rl/u50Va0ZDVfFudVDB1dPMlSwh8JFhgCI3LNNhjUDoJZ+UYGsiZ5gXGoXMVlPL2dHkCG2KE6arxtkk2F7dJytBgqTap4iI0q5sOM8e1N+ejy5Hs6xmt/bgQhGf03MdEFue5fStXCWPMYg+WaxXGzvG7P+x01nnyXuu88v2pXgC6b522kx2s+7HO/f+PJr8AJ9XOwJqr26NeJ4qWAFXkeOCDpmUMB7P3ZY/XRWJp2isQSFh0dxe2iV7tHxTMEnd7dBJqbOmTL2zpMUy/M24o2nyaMyj4RxhjPCrm8xIklgrIWnd7TK/5bwxJFACqPowO3ha8w0iLVyuTPs00/bIy70+UOzowcwnFdygNbUhbvBJuDhRQo9L6k189QoVM3A1oY+VD4Et6bocFgp8ZYWf/aNfNhL965pRqAErrF5zqLl8qhroxK7wWao+clAi6JAOcNWM= brian@laptop.milco.info
    loginshell: zsh
    password: "{{ ipa_new_user_password }}"

  - name: "{{ ipa_lookup_user }}"
    givenname: LDAP
    surname: Lookup
    email:
      - admin@milco.info
    password: "{{ ipa_lookup_password }}"

  - name: john.smith
    givenname: John
    surname: Smith
    email:
      - johnsmith@milco.info
    sshkeys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDD2LgGJ9phE2R9zosHKQO9UuNgK9NnC1lJMER7VVWgo90ESs73PZL70Ia8cj43Rl/u50Va0ZDVfFudVDB1dPMlSwh8JFhgCI3LNNhjUDoJZ+UYGsiZ5gXGoXMVlPL2dHkCG2KE6arxtkk2F7dJytBgqTap4iI0q5sOM8e1N+ejy5Hs6xmt/bgQhGf03MdEFue5fStXCWPMYg+WaxXGzvG7P+x01nnyXuu88v2pXgC6b522kx2s+7HO/f+PJr8AJ9XOwJqr26NeJ4qWAFXkeOCDpmUMB7P3ZY/XRWJp2isQSFh0dxe2iV7tHxTMEnd7dBJqbOmTL2zpMUy/M24o2nyaMyj4RxhjPCrm8xIklgrIWnd7TK/5bwxJFACqPowO3ha8w0iLVyuTPs00/bIy70+UOzowcwnFdygNbUhbvBJuDhRQo9L6k189QoVM3A1oY+VD4Et6bocFgp8ZYWf/aNfNhL965pRqAErrF5zqLl8qhroxK7wWao+clAi6JAOcNWM= brian@laptop.milco.info
    password: "{{ ipa_new_user_password }}"

ipa_hosts:
  - name: k8sm
    description: k8s primary master
    ip_address: 192.168.1.5
    ns_os_version: RHEL8
    mac_address:
      - "98:fa:9b:0a:ff:11"

  - name: k8s1
    description: k8s worker
    ip_address: 192.168.1.11
    ns_os_version: RHEL8
    mac_address:
      - "6c:4b:90:e2:89:09"
  - name: k8s2
    description: k8s worker
    ip_address: 192.168.1.12
    ns_os_version: RHEL8
    mac_address:
      - "98:fa:9b:f4:49:44"

  - name: laptop
    description: personal laptop
    ip_address: 192.168.1.75
    ns_os_version: Kubuntu 20.04
    mac_address:
      - "54:26:96:e0:51:53"

ipa_hostgroups:
  - name: k8s_platforms
    hostgroups: []
    hosts:
      - k8sm.milco.info
      - k8s1.milco.info
      - k8s2.milco.info
  - name: k8s_servers
    hostgroups:
      - k8s_platforms
    hosts: []
  - name: workstations
    hostgroups: []
    hosts:
      - laptop.milco.info

ipa_sudorules:
  - name: k8s_admins
    description: Allow k8s admins to sudo on k8s servers
    cmdcategory: all
    hosts:
    hostgroup:
      - k8s_servers
    usergroup: []
    sudoopt: []

ipa_reverse_dns:
  - name: '22'
    type: 'PTR'
    value: 'ipa'
  - name: '237'
    type: 'PTR'
    value: 'rhel8'

ipa_dnsrecords:
  - name: 'ipa'
    type: 'A'
    value: '{{ servers.ipa.ipv4 }}'
  - name: 'ipa'
    type: 'AAAA'
    value: '{{ servers.ipa.ipv6 }}'
