---


ipa_users:
  - name: "{{ ipa_lookup_user }}"
    givenname: LDAP
    surname: Lookup
    email:
      - admin@milco.info
    password: "{{ ipa_lookup_password }}"

ipa_sudorules:
  - name: k8s_admins
    description: Allow k8s admins to sudo on k8s servers
    cmdcategory: all
    hosts:
    hostgroup:
      - k8s_servers
    usergroup: []
    sudoopt: []

