---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: freeipa
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
        - env: prod
        - env: dev
  template:
    metadata:
      name: freeipa
    spec:
      syncPolicy:
        automated: {}
      project: freeipa
      destination:
        namespace: freeipa
        server: https://kubernetes.default.svc
      sources:
        - repoURL: https://github.com/ipenguin/bare-metal-kubernetes.git
          path: argo-apps/apps/freeipa
          targetRevision: HEAD
