---

- name: setup an IPA client
  hosts: "{{ ipa_client_nodes }}"
  vars_prompt:
    - name: ipa_client_nodes
      prompt: "Supply a host list:"
      default: ''
      private: no
  vars_files:
    - vaults/ipa.yml
  tasks:
    - name: install needed software
      apt:
        names:
          - sssd
          - freeipa-client
          - oddjob-mkhomedir
      when: ansible_os_family == "Debian"

    # TODO:
    # - name: add /etc/hosts records
    # - name: set dns to ipa server
    # - name: restart networking
    # - name: verify connection working

    - name: setup ipa to do authentication
      command: ipa-client-install -U --hostname={{ ansible_facts.fqdn }} \
               --mkhomedir --server={{ ipa_server_hostname }} --domain {{ lan_domain }} \
               --realm {{ ipa_domain | upper }} -p admin@{{ ipa_domain | upper }} -w {{ vault_ipa_admin_password }} \
               --ssh-trust-dns --enable-dns-updates --ntp-pool=rhel.pool.ntp.org

    - name: create home dir when ldap user logs in
      lineinfile:
        path: /usr/share/pam-configs/mkhomedir
        regexp: ''
        line: required pam_mkhomedir.so umask=0022 skel=/etc/skel

    - name: tell pam to update
      command: pam-auth-update #edit setup
