---

- name: install tools for clients
  hosts: k8sworkers
  tags:
    - rook_ceph
  tasks:
    - name: install lvm2
      apt:
        name:
          - lvm2
          - xfsprogs
        state: present
      when: ansible_os_family == "Debian"

- name: setup/destroy ceph data volumes
  hosts: k8scluster
  tags:
    - never
    - erase_data_vols
  tasks:
    - name: erase drives
      command: "sgdisk -Z /dev/{{ k8s_node_storage[ansible_hostname] }}"
    - name: delete rook configuration folder
      file:
        path: "/var/lib/rook"
        state: absent
    # - name: create basic mbr partion
    #   community.general.parted:
    #     device: /dev/{{ k8s_node_storage[host] }}
    #     label: msdos

- name: configure rook
  hosts: k8smasters
  become: no
  tasks:
    - name: include role for rook setup
      include_role:
        name: rook
