---

#
# Core instruments and tools for running
# and managing kubernetes
#

- name: setup rook-ceph
  include_tasks: k8s-rook.yml

- name: setup metrics server
  include_tasks: k8s-metrics-server.yml

- name: include prometheus monitoring
  include_tasks: k8s-prometheus.yml

#
# Other useful services
#

- name: setup IPA server
  include_tasks: ipa-setup.yml

#
# Software deployed on top of kubernetes
#
- name: setup nfs server
  include_tasks: k8s-deploy-nfs.yml

- name: setup git server
  include_tasks: k8s-deploy-gitea.yml

- name: setup jenkins CI/CD server
  include_tasks: k8s-deploy-jenkins.yml

- name: setup concourse CI/CD server
  include_tasks: k8s-deploy-concourse.yml

- name: setup
