---
#
# Network Definition:
# 1-19    - physical devices and hosts
# 20-100  - virtual servers and services
# 101-254 - other devices
#

ipv4_network: 10.1.1
ipv6_network: "{{ vault_ipv6_network }}"

network_services:
  ingress:
    ipv4: "{{ ipv4_network }}.20"
    ipv6: "{{ ipv6_network }}::20"
  s3:
    ipv4: "{{ ipv4_network }}.21"
    ipv6: "{{ ipv6_network }}::21"
  ipa:
    ipv4: "{{ ipv4_network }}.22"
    ipv6: "{{ ipv6_network }}::22"
  gitea:
    ipv4: "{{ ipv4_network }}.23"
    ipv6: "{{ ipv6_network }}::23"

network:
  ipv4:
    external_dns:
      - 1.1.1.3
      - 1.0.0.3
      - "/{{ lan_domain }}/{{ network_services.ipa.ipv4 }}"
    subnet: "{{ ipv4_network }}.0/24"
    router: "{{ ipv4_network }}.1"
    dns: "{{ ipv4_network }}.1"
    server_pool:
      start: "{{ ipv4_network }}.20"
      end: "{{ ipv4_network }}.100"
  ipv6:
    external_dns:
      - 2606:4700:4700::1113
      - 2606:4700:4700::1003
      - "/{{ lan_domain }}/{{ network_services.ipa.ipv6 }}"
    subnet: "{{ ipv6_network }}::/64"
    router: "{{ ipv6_network }}::1"
    dns: "{{ ipv6_network }}::1"
    server_pool:
      start: "{{ ipv6_network }}::20"
      end: "{{ ipv6_network }}::100"

router:
  ula_prefix: "fd5b:996d:3c79::/48"
  interfaces:
    - name: loopback
      dev: lo
      proto: static
      ipv4: 127.0.0.1
      netmask: 255.0.0.0
    - name: lan
      dev: br-lan
      proto: static
      netmask: 255.255.255.0
      ipv4: "{{ network.ipv4.router }}"
      ip6assign: 64
      dns_search: "{{ lan_domain }}"
    - name: wan
      dev: wan
      proto: dhcp
      peerdns: 0
      dns_servers: "{{ network.ipv4.external_dns }}"
    - name: wan6
      dev: wan
      proto: dhcpv6
      reqaddress: try
      reqprefix: 60
      peerdns: 0
      dns_search: "{{ lan_domain }}"
      dns_servers: "{{ network.ipv6.external_dns }}"
    # - name: vpn
    #   proto: wireguard
    #   ip6assign: 64
    #   private_key: "{{ vault_wireguard_private_key }}"
    #   # preshared_key: "{{ vault_wireguard_preshared_key }}"
    #   # port: 51820
    #   addresses:
    #     - 10.1.2.1/24
    #     - fd00:10:1:2::1/128
  devices:
    - name: wan
      mac: 18:fd:74:38:8a:d7
    - name: lan2
      mac: 18:fd:74:38:8a:d8
    - name: lan3
      mac: 18:fd:74:38:8a:d8
    - name: lan4
      mac: 18:fd:74:38:8a:d8
    - name: lan5
      mac: 18:fd:74:38:8a:d8
    - name: br-lan
      type: bridge
      ports:
        - lan2
        - lan3
        - lan4
        - lan5

hosts:
  - name: c1
    mac: 98:FA:9B:0A:FF:11
    ipv4: "{{ ipv4_network }}.5"
    duid: 00020000ab11451a71d26340b5e9
    hostid: 5
  - name: w1
    mac: 6C:4B:90:E2:89:09
    ipv4: "{{ ipv4_network }}.6"
    duid: 00020000ab1175c83adfb7ad202e
    hostid: 6
  - name: w2
    mac: 98:FA:9B:F4:49:44
    ipv4: "{{ ipv4_network }}.7"
    duid: 00020000ab116813038d3751bbec
    hostid: 7
  - name: laptop
    mac: 7c:21:4a:a2:99:af
    ipv4: "{{ ipv4_network }}.75"
    duid: 0004b4f7440dd7e55228828606dbc77a3c1e
    hostid: fade
  - name: printer
    mac: f4:ce:46:3e:f0:40
    ipv4: "{{ ipv4_network }}.9"
domains:
  - name: "ipa-01.{{ lan_domain }}"
    ipv4: "{{ network_services.ipa.ipv4 }}"
    ipv6: "{{ network_services.ipa.ipv6 }}"