---
#
# Network Definition:
# 1-19    - physical devices and hosts
# 20-100  - virtual servers and services
# 101-254 - other devices
#

ipv4_network: 10.1.1
ipv6_network: "{{ vault_ipv6_network }}"

#
# IMPROVE: simplify services structure across all plays.
# IMPROVE: remove many and use LB/Ingress IPs to create DNS entry.
#
network_services:
  vip:
    ipv4: "{{ ipv4_network }}.20"
    ipv6: "{{ ipv6_network }}::20"
  ingress:
    ipv4: "{{ ipv4_network }}.21"
    ipv6: "{{ ipv6_network }}::21"
  s3:
    ipv4: "{{ ipv4_network }}.22"
    ipv6: "{{ ipv6_network }}::22"
  ipa-01:
    ipv4: "{{ ipv4_network }}.23"
    ipv6: "{{ ipv6_network }}::23"
  ipa-02:
    ipv4: "{{ ipv4_network }}.24"
    ipv6: "{{ ipv6_network }}::24"
  sso:
    ipv4: "{{ ipv4_network }}.25"
    ipv6: "{{ ipv6_network }}::25"
  argo:
    ipv4: "{{ ipv4_network }}.26"
    ipv6: "{{ ipv6_network }}::26"
  gitea:
    ipv4: "{{ ipv4_network }}.35"
    ipv6: "{{ ipv6_network }}::35"

network:
  ipv4:
    external_dns:
      - 1.1.1.3
      - 1.0.0.3
      - "/{{ lan_domain }}/{{ network_services['ipa-01'].ipv4 }}"
    subnet: "{{ ipv4_network }}.0/24"
    router: "{{ ipv4_network }}.1"
    dns: "{{ ipv4_network }}.1"
    server_pool:
      start: "{{ ipv4_network }}.20"
      end: "{{ ipv4_network }}.100"
  ipv6:
    external_dns:
      - 2606:4700:4700::1113
      - 2606:4700:4700::1003
      - "/{{ lan_domain }}/{{ network_services['ipa-01'].ipv6 }}"
    subnet: "{{ ipv6_network }}::/64"
    router: "{{ ipv6_network }}::1"
    dns: "{{ ipv6_network }}::1"
    server_pool:
      start: "{{ ipv6_network }}::20"
      end: "{{ ipv6_network }}::100"

router:
  ula_prefix: "fd5b:996d:3c79::/48"
  interfaces:
    - name: loopback
      dev: lo
      proto: static
      ipv4: 127.0.0.1
      netmask: 255.0.0.0
    - name: lan
      dev: br-lan
      proto: static
      netmask: 255.255.255.0
      ipv4: "{{ network.ipv4.router }}"
      ip6assign: 64
      dns_search: "{{ lan_domain }}"
    - name: wan
      dev: wan
      proto: dhcp
      peerdns: 0
      dns_servers: "{{ network.ipv4.external_dns }}"
    - name: wan6
      dev: wan
      proto: dhcpv6
      reqaddress: try
      reqprefix: 60
      peerdns: 0
      dns_search: "{{ lan_domain }}"
      dns_servers: "{{ network.ipv6.external_dns }}"
    # - name: vpn
    #   proto: wireguard
    #   ip6assign: 64
    #   private_key: "{{ vault_wireguard_private_key }}"
    #   # preshared_key: "{{ vault_wireguard_preshared_key }}"
    #   # port: 51820
    #   addresses:
    #     - 10.1.2.1/24
    #     - fd00:10:1:2::1/128
  devices:
    - name: wan
      mac: 18:fd:74:38:8a:d7
    - name: lan2
      mac: 18:fd:74:38:8a:d8
    - name: lan3
      mac: 18:fd:74:38:8a:d8
    - name: lan4
      mac: 18:fd:74:38:8a:d8
    - name: lan5
      mac: 18:fd:74:38:8a:d8
    - name: br-lan
      type: bridge
      ports:
        - lan2
        - lan3
        - lan4
        - lan5

hosts:
  - name: r
    mac: 18:FD:74:38:8A:D8
    ipv4: "{{ ipv4_network }}.1"
  - name: sw1
    mac: 34:98:B5:A0:62:8E
    ipv4: "{{ ipv4_network }}.2"
  - name: ap1
    mac: F0:2F:74:92:A0:20
    ipv4: "{{ ipv4_network }}.3"
  - name: c1
    mac: 1C:FD:08:7C:08:BC
    #mac: 98:FA:9B:0A:FF:11
    ipv4: "{{ ipv4_network }}.10"
    duid: 00020000ab11ee035c834eb2cbc1
    hostid: 10
  - name: c2
    mac: 1C:FD:08:7C:08:E2
    #mac: 6C:4B:90:E2:89:09
    ipv4: "{{ ipv4_network }}.11"
    duid: 00020000ab1141e3610454d8e45d
    hostid: 11
  - name: c3
    mac: 1C:FD:08:7C:08:7D
    #mac: 98:FA:9B:F4:49:44
    ipv4: "{{ ipv4_network }}.12"
    duid: 00020000ab11107a31861e9e07b0
    hostid: 12
  - name: w1
    mac: 04:7B:CB:A2:67:49
    ipv4: "{{ ipv4_network }}.13"
    duid: 00020000ab115ab5348f3a9b65d1
    hostid: 13
  - name: w2
    mac: 04:7B:CB:A2:66:13
    ipv4: "{{ ipv4_network }}.14"
    duid: 00020000ab11642704f6e5c98bc3
    hostid: 14
  - name: w3
    mac: 04:7B:CB:A2:66:FA
    ipv4: "{{ ipv4_network }}.15"
    duid: 00020000ab11d55a3eb23fba8a04
    hostid: 15
  - name: w4
    mac: 84:47:09:1D:2B:11
    ipv4: "{{ ipv4_network }}.16"
    duid: 00020000ab11e2b7d21dd313dabc
    hostid: 16

domains:
  - name: "ipa-01.{{ lan_domain }}"
    ipv4: "{{ network_services['ipa-01'].ipv4 }}"
    ipv6: "{{ network_services['ipa-01'].ipv6 }}"
  - name: "{{ k8s_api_endpoint }}"
    ipv4: "{{ network_services['vip'].ipv4 }}"
    ipv6: "{{ network_services['vip'].ipv6 }}"