common_utils:
  - fwupdate
  - gdisk
  - git
  - htop
  - iperf
  - r8125-dkms
  - rsync
  - smartmontools
  - sysstat
  - tmux
  - vim
  - zip
  - zsh

debian_utils:
  - freeipa-client
  - libvirt-daemon
  - libvirt-daemon-system
  - lvm2
  - nfs-common
  - python3-packaging
  - python3-kubernetes
  - xfsprogs

pip_packages: []
