---
- name: populate facts
  ansible.builtin.setup:

- name: Create directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: root
    group: root
    mode: "{{ item.mode }}"
  loop:
    - { path: "/etc/kubernetes", mode: '0755' }
    - { path: "/etc/kubernetes/manifests", mode: '0700' }
  when:
    - inventory_hostname in groups['controllers']

- name: dns lookup
  ansible.builtin.command:
    cmd: dig +short {{ item }} @{{ network.ipv4.dns }}
  register: dns_results
  loop: "{{ groups['controllers'] }}"

- name: Install Kube VIP
  ansible.builtin.template:
    src: kube-vip.yaml.j2
    dest: /etc/kubernetes/manifests/kube-vip.yaml
    owner: root
    group: root
    mode: 0600
  vars:
    dns_entries: '{{ dns_results.results }}'
  when:
    - inventory_hostname in groups['controllers']
