---

- name: create rook-ceph namespace
  kubernetes.core.k8s:
    name: rook-ceph
    api_version: v1
    kind: Namespace
    state: present

- name: Download rook ceph CRDs
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/rook/rook/v{{ rook_ceph_version }}/cluster/examples/kubernetes/ceph/crds.yaml
    dest: ~/crds.yml
    mode: '0644'
- name: Download rook ceph common
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/rook/rook/v{{ rook_ceph_version }}/cluster/examples/kubernetes/ceph/common.yaml
    dest: ~/common.yml
    mode: '0644'
- name: Download rook ceph operator
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/rook/rook/v{{ rook_ceph_version }}/cluster/examples/kubernetes/ceph/operator.yaml
    dest: ~/operator.yml
    mode: '0644'

- name: create rook ceph CRDs
  kubernetes.core.k8s:
    state: present
    src: ~/crds.yml
- name: create rook ceph commons
  kubernetes.core.k8s:
    state: present
    src: ~/common.yml
- name: create rook ceph operator
  kubernetes.core.k8s:
    state: present
    src: ~/operator.yml

- name: create rook ceph server & tools
  kubernetes.core.k8s:
    state: present
    template: "{{ item }}"
  loop:
    - rook-ceph.yml
    - rook-tools.yml
