---
# tasks file for metrics-server

- name: create folder
  file:
    path: "{{ pod_data_path }}/metrics"
    state: directory

- name: copy in config file
  template:
    src: metrics-server-{{ metrics_version }}.yaml
    dest: /home/{{ ansible_user }}/metrics-server.yaml

- name: deploy metrics server
  become: no
  command: kubectl apply -f metrics-server.yaml
