apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: v{{ kubernetes_version }}
networking:
  podSubnet: {{ k8s_pod_network.ipv4 }}{% if k8s_use_ipv6 %},{{ k8s_pod_network.ipv6 }}{% endif %}

  serviceSubnet: {{ k8s_service_network.ipv4 }}{% if k8s_use_ipv6 %},{{ k8s_service_network.ipv6 }}{% endif %}

{% if k8s_use_ipv6 %}
featureGates:
  IPv6DualStack: true
{% endif %}

# Used for NFS provisioning with Rook, this will be removed if Rook doesn't update code.
#RemoveSelfLink: false
apiServer:
  extraArgs:
    feature-gates: RemoveSelfLink=true{% if k8s_use_ipv6 %},IPv6DualStack=true{% endif %}

controllerManager:
  extraArgs:
    feature-gates: RemoveSelfLink=true{% if k8s_use_ipv6 %},IPv6DualStack=true{% endif %}

scheduler:
  extraArgs:
    feature-gates: RemoveSelfLink=true{% if k8s_use_ipv6 %},IPv6DualStack=true{% endif %}

---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
cgroupDriver: systemd
