---

- name: restart networking to load new protocol
  ansible.builtin.raw: /etc/init.d/network restart

- name: Configure network interfaces
  ansible.builtin.template:
    src: network.j2
    dest: /etc/config/network
    owner: root
    group: root
    mode: '0600'
  notify: restart network

...