---

- name: install docker on redhat
  import_tasks: redhat.yml
  when:
    - ansible_os_family == "RedHat"

- name: install docker on debian
  import_tasks: debian.yml
  when:
    - ansible_os_family == "Debian"

- name: "add {{ ansible_user }} to docker group"
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: install docker compose
  uri:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_ver }}/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}
    dest: /usr/local/bin/docker-compose
    mode: '0755'
    status_code:
      - 200
      - 304
  when: ansible_architecture == "x86_64"

- name: create link for docker-compose
  file:
    path: /usr/bin/docker-compose
    src: /usr/local/bin/docker-compose
    state: link
  when: ansible_architecture == "x86_64"

- name: enable docker service
  service:
    name: docker
    state: started
    enabled: yes
