---

- name: Add Harbor helm repo
  kubernetes.core.helm_repository:
    state: present
    name: harbor
    repo_url: https://helm.goharbor.io

- name: create harbor namespace
  kubernetes.core.k8s:
    kind: Namespace
    name: "{{ harbor_namespace }}"
    state: present

- name: Create Harbor storage bucket
  kubernetes.core.k8s:
    state: present
    template: harbor-bucket.yaml.j2

- name: Pause while the bucket is created
  kubernetes.core.k8s_info:
    kind: ObjectBucketClaim
    wait: true
    name: "{{ harbor_bucket_name }}"
    namespace: "{{ harbor_namespace }}"
    wait_sleep: 5
    wait_timeout: 30

- name: Get bucket info
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    name: "{{ harbor_bucket_name }}"
    namespace: "{{ harbor_namespace }}"
  register: _bucket_creds

- name: Deploy Harbor helm chart
  kubernetes.core.helm:
    name: harbor
    chart_version: "v{{ harbor_version }}"
    chart_ref: harbor/harbor
    release_namespace: "{{ harbor_namespace }}"
    create_namespace: true
    values: "{{ lookup('template', 'harbor-values.yaml.j2') | from_yaml }}"
  vars:
    s3_access_key: "{{ _bucket_creds.resources[0].data.AWS_ACCESS_KEY_ID | b64decode }}"
    s3_secret_key: "{{ _bucket_creds.resources[0].data.AWS_SECRET_ACCESS_KEY | b64decode }}"
