---
# tasks file for freeipa

- name: install RedHat pip files
  yum:
    name:
      - python3-pip
    state: present
  when: ansible_os_family == "RedHat"

- name: install Ubuntu pip files
  apt:
    name:
      - python-pip
    state: present
  when: ansible_os_family == "Debian"

- name: install docker library pip
  pip:
    name: docker

- name: create storage space
  tags:
    - container_only
  file:
    path: "{{ ipa_storage_dir }}"
    state: directory
    owner: root
    group: root
    mode: '0750'

- name: Create freeipa container
  tags:
    - container_only
  community.docker.docker_container:
    name: freeipa
    image: "freeipa/freeipa-server:{{ ipa_docker_version }}"
    container_default_behavior: no_defaults
    hostname: "{{ ipa_server_hostname }}"
    state: started
    restart: yes
    restart_policy: always
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - "{{ ipa_storage_dir }}:/data:Z"
    env:
      IPA_SERVER_HOSTNAME: "{{ ipa_server_hostname }}"
    sysctls:
      net.ipv6.conf.all.disable_ipv6: "0"
    ports:
      - "{{ ipa_ipv4 }}:53:53"       #dns
      - "{{ ipa_ipv4 }}:53:53/udp"   #dns
      - "{{ ipa_ipv4 }}:80:80"       #http
      - "{{ ipa_ipv4 }}:443:443"     #https
      - "{{ ipa_ipv4 }}:389:389"     #ldap
      - "{{ ipa_ipv4 }}:636:636"     #ldaps
      - "{{ ipa_ipv4 }}:88:88"       #kerberos
      - "{{ ipa_ipv4 }}:88:88/udp"   #kerberos
      - "{{ ipa_ipv4 }}:464:464"     #kpasswd
      - "{{ ipa_ipv4 }}:464:464/udp" #kpasswd
      - "{{ ipa_ipv4 }}:123:123/udp" #ntp
      - "[{{ ipa_ipv6 }}]:53:53"       #dns
      - "[{{ ipa_ipv6 }}]:53:53/udp"   #dns
      - "[{{ ipa_ipv6 }}]:80:80"       #http
      - "[{{ ipa_ipv6 }}]:443:443"     #https
      - "[{{ ipa_ipv6 }}]:389:389"     #ldap
      - "[{{ ipa_ipv6 }}]:636:636"     #ldaps
      - "[{{ ipa_ipv6 }}]:88:88"       #kerberos
      - "[{{ ipa_ipv6 }}]:88:88/udp"   #kerberos
      - "[{{ ipa_ipv6 }}]:464:464"     #kpasswd
      - "[{{ ipa_ipv6 }}]:464:464/udp" #kpasswd
      - "[{{ ipa_ipv6 }}]:123:123/udp" #ntp
