---

- name: Install DDNS packages
  ansible.builtin.raw: |-
      opkg install luci-app-ddns

- name: Configure dynamic DNS
  ansible.builtin.template:
    src: ddns.j2
    dest: /etc/config/ddns
    owner: root
    group: root
    mode: '0600'
  notify: restart ddns