---

- name: Configure dnsmasq
  ansible.builtin.template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    owner: root
    group: root
    mode: '0600'
    validate: 'dnsmasq --test -C %s'
  notify: restart dnsmasq
