---

- name: Combine hosts lists
  ansible.builtin.set_fact:
    _hosts: "{{ hosts + vault_hosts }}"

- name: Configure dhcp
  ansible.builtin.template:
    src: dhcp.j2
    dest: /etc/config/dhcp
    owner: root
    group: root
    mode: '0600'
  notify: restart dnsmasq
