---

ceph_version: 17.2.5
cert_manager_version: 1.11.1
cilium_version: 0.13.1
cilium_helm_version: 1.13.1
containerd_version: 1.7.0
crio_version: 1.24.5~0

etcd_version: 3.5.6-0

freeipa_version: 4.10.1

gitea_helm_chart_version: 8.0.2
gitea_version: 1.19.0

helm_version: 3.11.2

ingress_nginx_version: 4.6.0

kubernetes_version: 1.26.3

metallb_version: 0.13.9

rook_version: 1.11.3
...